% select serial port
% Note: use serialportlist() to check for available serial ports
serialPortName = "COM3";

% define packet specifier
packetSpec = {'2*single', 'single', 'single', 'single','single','single'};

% select baud rate
baudRate = 38400;

% configure scopes
plotsGridSize = [6, 1];
plotsContentList = [ ...
    1, 1, 1; ... % format: scope id, signal id, component id
    1, 1, 2; ... %
    1, 6, 1; ... %
    2, 2, 1; ... %
    3, 3, 1; ... %
    4, 4, 1; ... %
    5, 5, 1];    %

% start serialDataLoggerApp with specified input arguments
serialDataLoggerApp( ...
    "SerialPortName", serialPortName, ...
    "PacketSpec", packetSpec, ...
    "BaudRate", baudRate, ...
    "EnableStartStopCmds", true, ...
    "TxStartCmd", 65, ...
    "TxStopCmd", 66, ...
    "EnableCOBS", true, ...
    "EnableNullTerminator", true, ...
    "BufferSize", 10000, ...
    "TxSampleTime", 0.01, ...
    "EnableLogToWorkspace", true, ...
    "EnableSaveOnExit", true, ...
    "VarName", "data", ...
    "PlotsGridSize", plotsGridSize, ...
    "PlotsContentList", plotsContentList, ...
    "PlotsDuration", 5, ...
    "PlotsRefreshRatio", 8);