
clear all; clc;

plottaDatiDaMat('es6.mat', {'ref_30', 'A_30', 'A_wF30'}, ...
                           {'Reference', 'Sim. (no Friction)' 'Sim. (with Friction)'}, ...
                           '6) Amplitude 30', 'Position [deg]');

plottaDatiDaMat('es6.mat', {'ref_60', 'A_60', 'A_wF60'}, ...
                           {'Reference', 'Sim. (no Friction)' 'Sim. (with Friction)'}, ...
                           '&) Amplitude 60', 'Position [deg]');

plottaDatiDaMat('es6.mat', {'ref_90', 'A_90', 'A_wF90'}, ...
                           {'Reference', 'Sim. (no Friction)' 'Sim. (with Friction)'}, ...
                           '6) Amplitude 90', 'Position [deg]');



plottaDatiDaMat('es7.mat', {'err6','err7'}, ...
                           {'error point 6', 'error point 7'}, ...
                           '7) Error', 'Error [deg]');
plottaDatiDaMat('es8.mat', {'ref','step40'}, ...
                           {'Reference', 'Sim.'}, ...
                           '8)', 'Position [deg]');
%plottaDatiDaMat('es8.mat',{'ref','step40'});